spring:
  data:
    redis:
      host: 14.103.49.202
      port: 6379
      ### Redis数据库索引(默认为0)
      database: 0
      ### 连接超时时间（毫秒）
      timeout: 60000ms
      password: Kk^%HtEJuGHU%3HT
      lettuce:
        pool:
          ### 最大连接数（使用负值表示没有限制） 默认8
          max-active: 8
          ### 最小空闲连接  默认8
          min-idle: 0
          ### 连接池中的最大空闲连接 默认8
          max-idle: 8
          ### 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

redis:
  key: redis.cache.
  paramKey: redis.param.initCache
  permissionKey: redis.permission.initCache
  productKey: redis.product.initCache
  value: 1
  expirationTime: 180
  paramCache: redis.param.cache
  permissionCache: redis.permission.cache
  productCache: redis.product.cache
